### ISSUE TITLE
`serve` in root workspace is not working

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/remix-server#4]
> Error: ENOENT: no such file or directory, open '/Users/user/remix-server/apps/cms/dist/seed/payload.jpg'

**Comment by dsod** [comment]
Hi,

Thanks for taking your time to create this issue.
This happens when your DB is clean and you run `pnpm run serve` from the root, like you described. Due to the application being served from `apps/cms/dist` and static files such as images is not copied over to the server bundle when running `pnpm run build`, it is missing.

The seed-script was not really intended for production use. I've changed this (f7c6b37e319c9618a5fdb49e61753724dc8f5a53), so that the seed script only runs in development mode.

If you want to do this for production as well, you could simply add another `copyfiles` statement in the `apps/cms/package.json > scripts.copyfiles` statement, to move static files into the `dist/` folder, as well as the `build/` folder.
